label google_test:
    Lars "Discere, cogitare, agere- the triad of wisdom. Learning enriches the mind, and thinking sharpens it, but it is through action that we truly manifest our knowledge and shape our reality."

    Lars "One would think that a merchant guild wouldn’t bother creating such a philosophical motto and instead advertise 1+1 dragon ship seats every holiday season."

    Lars "We could even offer complementary Earth meals made by the human chefs who arrived to Zephyr through the connecting chain of reincarnation between our two realms."

    Lars "But then again, we wouldn’t be embarking on artifact hunts and treasure expeditions if our guild’s only purpose was commerce."

    "Unknown" "Our dearest Captain Lars! Are you mumbling to yourself again?"

    Lars "Looks like one, or should I say, the only passenger has woken up. It’s a wonder how he managed to stay asleep throughout our entire journey without any proper seat arrangements or resting areas."

    Lars "But then again, Sir Claude is notorious for being resourceful in such moments owning up to his history of travels and adventurous ordeals throughout Zephyr. Despite his comfortable upbringings, he’s capable of sleeping like a koala descendent without any complaints."

    Claude "Or are you whispering trade-secret shortcuts to your, or more so, MY lovely dragon, Spotsy?"

    Lars "No whispering is needed, when you can talk telepathically as a dragon pilot… is what I’d like to retort."

    Lars "However, it always eased the mind of passengers when they saw the communication procedure itself. Even for someone with an arrogant persona like Sir Claude."

    Lars "It’s not an everyday luxury to ride dragon ships, and as pilots and trainers, we had the duty of making sure our customers felt safe and secure during their once-in-a-lifetime experience."

    Lars "Throughout such theatrics, I enjoyed seeing descendants and humans alike embrace a smile while under my care. It reminded me of how I adhered to my parents’ philosophy of being the bridge between dragons and passengers."

    Lars "Bad at naming as always, Sir Claude. Especially for this fine species of polka dot ruby fireblazer."

    Lars "I gently caressed the head of our newest guild member and she, in turn, closed her eyes in a captivating display of trust. Looks like she’s already won over my heart."

    Lars "See how these scales are gleaming with a crimson hue? As she breathes, the intense heat generated by her metabolism can cause the air pockets under her scales to shimmer and expand. These ruby distortions aren’t for mere show either, Guild master Sylvian mentioned that certain blacksmiths can use the ensuing heat for their forging practices. I studied a lot about this since Rory mentioned she wanted to help out her family, and you know how she can be as stubborn as a mule. Well, she’s technically a bull descendent so that’s beside the point but-"

    Claude "Focus on your dragon steering Captain! I wouldn’t want to be that poor passenger who reincarnates early to the Earth realm just because you were adoring our newest ship."

    Lars "Hearing Sir Claude’s loud exclamation, Spotsy’s body jumped a little and her eyes once again focused on the landscape. The sunrise was nearing as colorful hues of crimson and gold took over the sky before us."

    Claude "I did make quite an effort to negotiate for her, after all."

    Claude "But this wouldn’t be the first dragon ship I’ve acquired. I need a new challenge after the last one..."

    Lars "I want to retort that his challenge could have been extra negotiations for an extra package of seats and commodities instead of a nameless artifact and one travel mat."

    Lars "However, in doing so, I have to keep in mind that his considerate nature outshines his egotistical streak in such situations. Seeing as he gave me the single rug we had, to rest on, during our journey."

    Lars "Ever since, he has been leaning on Spotsy’s back spines without any proper equipment. Not the most comfortable position to wish for let alone suffer through, for hours on end."

    Lars "Sir Claude always knew how to watch out for those around him even if he was occupied with bolstering himself instead."

    Lars "However, I couldn’t help but admire his selfless acts in moments like this where there wasn’t anyone to soundly praise his efforts."

    Lars "Maybe it was something he personally enjoyed and took pride in because no matter the protest I made for him to take back the mat to rest on, he would masterfully steer the conversation in a way that I’d end up embarrassed in making the request."

    Lars "Shhh Sir Claude! You’re going to hurt Spotsy’s feelings. Not to mention, she’ll get confused and make a false move if you don’t stop bothering me."

    Lars "The tabloids would have a field day if you were to fall off under these conditions."

    Lars "I crossed my arms at Sir Claude. I had to make him understand the seriousness of the situation. Yet, whenever I tried to be extra serious, I ended up getting more anxious instead."

    Lars "His teasing will have no end if he catches my tail flailing due to stress. Which is why I have to hold my russet-colored tail still. There’s no controlling the fox ears, but hopefully, they don’t start drooping."

    Lars "More importantly, Guild master Sylvian would be quite upset if our guild got noticed only for your publicity stunt."

    Lars "Sir Claude brought up his hand to his chest to make a show of how my comments offended him, as always. His mouth was agape in shock and he started shaking his head at me."

    Claude "Tsk, tsk, Captain, you should know that a few gossiping papers doesn’t make any difference for me."

    Claude "Not because all publicity is good publicity, that’s just a standard industry cliché."

    Claude "It’s because I only ever seek to be the greatest merchant there is and I will use every tool at my disposal to achieve it."

    Lars "Bold statements for an equally bold merchant and adventurer. Another quality of his that I liked to see and learn from. His ambition knew no bounds and it’s always good to be determined in a field full of dragon trainers, companions, and pilots."

    Lars "Really? I didn’t know our young master liked being the center of attention. You always seem to be hiding that you’re the only heir of the infamous Dupont merchant family. At first, I thought it was so there wouldn’t be any rumors of our Guild being associated with your family name, but you’ve always been acting suspiciously about it. You never seem to give out your last name during our expeditions or client meetings and-"

    Claude "Captain, I didn’t think that you were interested in my personal life all that much."

    Lars "Woah! When did he close the gap between us? Was it when I was mindlessly rambling? His forehead was nearly touching mine and not to mention, those golden eyes of his are staring right at me …"

    Claude "I could satisfy your curiosity by merely saying that I enjoy the challenge of making my own name."

    Claude "But then you’ll have to satisfy my curious question as well, which would be the reason behind your wagging tail that you’re so cutely trying to hide."

    Lars "I could feel myself instantly heat up in embarrassment. I took a quick look at tail behind me and it was wagging around like no tomorrow. Situations like this always me feel more nervous in return and I was sure that my fox ears had also drooped down in a similarly self-conscious fashion."

    Lars "My tails and ears both were characteristic unique to the fox descendants and no matter what I did, they always had a mind of their own."

    Lars "Sir Claude probably took notice to them way earlier than I did thanks to his ‘third eye’, a unique trait specific to lizard descendants which made them focus on objects up close and far away with ease, sense changes in light and darkness, and many more."

    Lars "I’ll have to distract him before he teases me again. There’s no stopping Sir Claude if his teasing turns to flirting. Only Rory and Master Sylvian have resistance to his charm, everyone else just gets seduced instead."

    Lars "THEN I SUPPOSE you’d have no problem if the headlines were to go like this-"

    Lars "‘The rising star, Claude from the infamous Dupont merchant family, tragically plummets to his death as a result of angering the fireblazer dragon ship captain. The tragic mistake of paying 250 thousand gold coins for a chance to reach the skies, only to plummet to the bottom of the sea and become a gourmet meal.’"

    Claude "Haha, my dear captain, are you planning to bankrupt the entire realm with those numbers?"

    Claude "Or did you hear them from your human passengers again?"

    Lars "Sir Claude stepped back, stretching his hand behind his head, and walked away. A hint of nostalgia and loneliness lingered in his eyes as he moved further from me."

    Claude "I’ve missed talking with them, but the recent seasonal galas are filling up my timetable."

    Claude "Not to mention our recent artifact negotiations…"

    Claude "A single necklace with no known origins, randomly appearing out of thin air. The seller was so adamant to wash his hands off of it that he was willing to add it as a complementary gift."

    Claude "His behavior was really suspicious but I couldn’t help accepting it out of curiosity even if I didn’t catch a glimpse of the jewelry itself."

    Lars "Suddenly, he halted, his gaze fixated upon the ornamental wooden box adorned with a mesmerizingly intricate design, positioned near his original seating spot."

    Lars "In that moment, a twinkle of curiosity ignited in his eyes, as if an adventurous spirit had awakened within him. It was as though he had already embarked on a mental journey, eager to unlock the mysteries concealed within every nook and cranny."

    Lars "In an instant, Sir Claude's attention snapped back to me, and a mischievous smile played upon his lips. The morning sunlight caught the glimmer of his silver braids, casting them in a radiant glow."

    Lars "With an unexpected burst of playful energy, he began to skip towards me with light steps. In no time, he closed the distance between us, leaning in closely, his presence captivating and magnetic."

    Claude "Besides, captain, you should know better than to recklessly use the Dupont last name."

    Lars "His fingertips gently brushed against my cheek, leaving a trail of warmth in their wake, as his golden eyes locked onto mine with unwavering intensity."

    Lars "His voice deepened, resonating with a seductive allure, as he leaned in, his lips tantalizingly close to my ear. In a hushed whisper, he breathed words that caressed the air and sent shivers down my spine."

    Claude "I prefer it when you say my name after all. It’s one of the tiny joys of my life."

    Lars "The sudden confession took me by surprise. Even though it wasn’t the first time that I heard Sir Claude make such a comment. He possesses a captivatingly flirtatious nature, effortlessly weaving his charm into every interaction."

    Lars "It is in the subtleties of his movements, the way his fingers gently graze a cheek or his voice dips into a velvety whisper, that his artistry truly blossoms."

    Lars "My fur prickles with anticipation, causing me to instinctively wave my arms in a feeble attempt to conceal my excited tail once again. I can sense my fox ears perked up, betraying my keen interest in Sir Claude's jests and teasing."

    Lars "However, a part of me hesitates, fearing that surrendering to his playful banter may lead to my own demise. As a result, I find myself stumbling over my words, caught in a tangled mess of stuttering syllables."

    Lars "W-w-what are you saying all of a sudden?! Did you lose your mind?"

    Lars "If you tease me again, I really won’t be able to guarantee your safety…"

    Lars "…so, s-stop it."

    Claude "Awe, is our captain getting shy all of a sudden? Did you know your ears get red when your embarrassed?"

    Lars "With little time to question his truthfulness, I instinctively place my hands upon my ears, hoping to shield any trace of vulnerability that might betray my reaction to Sir Claude’s words."

    Lars "You just keep spouting lies; I should know better than to trust your lizard tongue."

    Lars "I am a dragon pilot, an unwavering force soaring through the skies."

    Lars "My years of experience have honed my resilience and steeled my resolve. I cannot allow myself to be easily affected by the whimsical words of Sir Claude, no matter how charismatic he may be."

    Lars "After all, he’s only joking to gauge my reaction…"

    Lars "Sir Claude remains unfazed by my momentary embarrassment except for a triumphant smile."

    Lars "He had achieved what he sought after all – another victory in his competitive mind. His satisfaction in eliciting a reaction from me becomes clear, fueling his relentless pursuit of challenges."

    Claude "You know, if we ever crash, we could go down the reincarnation route together."

    Claude "I wouldn’t mind starting over as long as there’s something new to conquer. We would make quite the adventurous pair as well."

    Lars "In an unexpected shift, Claude's demeanor transforms, his expression taking on a more serious tone. His smile persists, but his gaze wanders into the distance, lost in a realm of contemplation that obscures the true weight and significance of his words. It's as if he momentarily retreats into the depths of his thoughts, delving into a realm known only to him."

    Claude "Life gets pretty boring when you have everything you need in the palm of your hand."

    Lars "Wait, does that have something to do with your family-"

    Claude "You know Captain-"

    Lars "As quickly as the shadow appears, it dissipates. Claude reverts to his usual carefree self, effortlessly resuming his charismatic disposition."

    Claude "Our mansions scholar, the Archmage of Zephyr, used to tell me that the upper echelon of humans on earth fly in the skies by genetically mutated wings, you could say it’s similar to what Boss Sylvian has. They can even turn their pets to humans while maintaining their innate animal traits such as ears, tails and more."

    Claude "In fact, you could be similar to one of their domesticated fox breeds and-"

    Lars "Not wasting a single breath, I dove straight into questioning Claude, eager to hear more of what he had to say. His masterful skill at steering away from certain topics didn't deter me; if anything, it fueled my curiosity even more."

    Lars "You’re lying! How on earth did they do that? You’re not teasing me like last time, are you?-"

    Lars "But before I could proceed, Sir Claude abruptly silenced me, placing his index finger gently on my lips. His touch, despite the cold shimmer of his scaly hands, carried a surprising warmth."

    Claude "As much as I hate to cut you off your cute rambling captain, I think we’ll have to save our conversation for later."

    Claude "Our dearest guild master’s staff is lighting our landing spot. You’ll be blinded by the number of sunflowers and roses he set up."

    Claude "His idea of guiding us with flowers colors is as gentle as always."

    Lars "I glanced downward; Our destination near the sea came into view, marked by a vibrant array of sunflowers and roses. Their vivid colors stood out, captivating the eye and creating a striking contrast against the backdrop."

    Lars "Ah, it’s a shame. I was hoping to learn something new. I have to reward Spotsy well when we get back."

    Claude "I’d be inclined to say that you didn’t manage to tap into our dragon’s full potential captain. Owning up to how I stole your attention for more than half, or better yet, the entire ride."

    Lars "Ugh, I should have pushed you off the dragon’s back myself-"

    Claude "However, since you managed to get us here without any dangerous maneuvers, I’ll allow you to be the first to touch our newest artifact."

    Claude "It’s the first time it’s made its way to our side of the realm, making the occasion quite momentous."

    Lars "As we descended, a long line of flowers guided us towards the landing spot. The proximity to the water offered a perfect opportunity for Spotsy to release some pent-up energy, allowing her to gracefully ease off steam and find solace in the calming embrace of the sea."

    Lars "As the sole passengers aboard the dragon ship, guiding Spotsy in her safe descent was a seamless task. Once we disembarked, our attention turned to a figure approaching us. Emerging from the surroundings, a tall and slender magician made their way towards our position."

    Lars "The guild master, known for his tradition of being the first to greet junior guild members upon their return from travels, approached us with a nod of acknowledgment towards Claude. A warm smile graced his lips as his obsidian wings fluttered gracefully."

    Lars "With a whispered incantation, the brim of his witch hat bloomed with a vibrant array of sunflowers and roses, their petals unfurling in a mesmerizing display."

    Lars "In one fluid motion, he extended the blossoms from his hat towards me, his gaze urging me to accept this symbolic gift. His eyes carried a blend of strength and kindness, assuring me of his unwavering support. It was a gesture that spoke volumes, embodying the guild's unity and camaraderie."

    "Unknown" "In a sky where dragons soar with grace, a guild of merchants finds its place. With sunflowers and roses in their hands, they guide passengers to enchanted lands."

    "Unknown" "Welcome back, dear members of “Custodes Sylvae”. I’m happy to see that you both landed safely."

    "Unknown" "Lars, your piloting was truly magnificent as always. It’s a sight that I’m honored to witness every time."

    Claude "It wouldn’t be a warm welcome if Master Sylvian weren’t here to recite his poetry. I missed having someone challenging to tease, Captain Lars over here is too gullible and makes it child play for me HAHAHA!"

    Lars "As Claude's laughter echoed through the air, a pang of discomfort coursed through me. Though I swiftly concealed my reaction, I couldn't help but feel a tinge of unease."

    Lars "Being likened to a child, especially by someone I held in regard, stirred a mix of emotions within me. It was a reminder of the delicate balance between admiration and the desire to be seen as an equal."

    Lars "Thank you, Master. I wish you could have joined us on the ride too. Sir Claude here almost caused us to plummet to our doom... twice."

    Claude "Eh, I did promise to reward you later, didn’t I? drum roll please ~"

    Lars "With a flourish of his hands, Sir Claude performed a series of gestures that mimicked a drumroll. Tension filled the air as anticipation built, drawing everyone's attention. Then, in a dramatic display, he spread his arms wide, revealing a moment of grand reveal…which was nothing?"

    Claude "Haha, I seem to have left it on the ship."

    Claude "Captain, could you be so kind as to bring our precious cargo?"

    "Sylvian" "Aren’t you tired from guiding our new dragon, Lars? I could easily fly and grab it for you."

    Lars "Would that be alright with you master? I’d like to spend some time with Sir Claude."

    "Sylvian" "I respect your choice Lars even though… uhm, never mind, I suggested it in the first place after all."

    "Sylvian" "Ehem! I’m sure Rory will arrive soon as well so you’ll get to spend some time with her as well."

    Claude "Awe, you choose to stay with me instead of Boss Sylvian, I’m touched Captain. I’ll have to give you a special reward later in private. We’ll be able to venture into a special realm together."

    Lars "His hands gently encircled my waist, drawing me closer to him. As his eyes, akin to pools of molten sunlight, met mine, a mischievous spark danced within them, hinting at his playful nature."

    Lars "Yet, beneath that playfulness, there lurked a subtle undertone of competition, evident in the way he regarded Master Sylvian."

    "Sylvian" "Claude, remember what I said about teasing him too much? Besides, if Rory catches you giving Lars trouble again..."

    Claude "Before worrying about Captain over here, you should head on to where Spotsy is resting, Boss. We wouldn’t want her to accidentally drop our gift to the depths of the sea."

    Lars "As Master Sylvian gracefully takes flight, his swan-like wings glistening in the sunlight, I can't help but admire the ethereal beauty of the scene. Petals cascade from his magician's hat, creating a trail of delicate grace as he departs."

    Lars "However, before I can fully immerse myself in the enchanting display, a sudden voice slices through the air with a chilling menace."

    "Rory" "Clauuudy~"

    Claude "Roryyy~"

    "Rory" "I believe I mentioned that if I ever catch you bossing Larsy around, I’d pluck out your lizard eyes to adorn my newest puppet, Agatha."

    "Rory" "You should know that my threats work quite effectively, especially with how Brittina’s puppet dress is shimmering with the scales you’ve kindly donated... in your sleep, of course."

    Lars "A figure emerges from where Master Sylvian stood just a few second ago, and to my pleasant surprise, it is none other than Rory, my childhood best friend. True to her lineage as a bull descendent, Rory possesses a fiery temperament and is quick to charge at those who annoy her."

    Lars "Our bond has withstood the test of time, and even though she and Claude have had a harsh relationship due to their prestigious family backgrounds and competitive nature. Yet, for the sake of our guild and the well-being of its members, they have found a way to coexist."

    Claude "If it isn’t our hot-tempered bull, breathing fire as soon as she lays eyes on me. It’s a pleasure to see you again, little Rory. Or should I say, a curse to behold?"

    "Rory" "Hoy! I told you never to call me that again! And doesn’t your receding hairline remind you that half your hair now belongs to Puppet Alex because you called me a midget last time?!"

    Claude "Now, now, I would have to say these finely braided silver strands that I’ve so kindly donated to you are what’s bringing half the revenue for your puppet shows, aren’t they little Rory?"

    "Rory" "I warned you not to call me that, you cheap lizard!"

    "Rory" "You really have the gall to be talking to me when all your travel funds are conveniently collected from my shows."

    "Rory" "For the sake of compensation, it’s time to say goodbye to Claude Junior with my nifty scissor too-"

    Lars "Thankfully, Master Sylvian swiftly intervenes, diffusing the tension with his timely return. In his grasp, he holds a grand and ornate box, its intricate design hinting at the secrets it conceals within. The weight of anticipation fills the air as all eyes turn to the box, momentarily diverting attention from the conflict."

    "Sylvian" "I’m back with the cargo!"

    "Rory" "Larsy, you’re here! Awe, I missed you so much. One more minute with my arch-nemesis over here and his rag-like face would be honored by my vomit."

    Lars "Come on Rory, you don’t really mean that."

    "Rory" "I have never meant anything more in all my bull years."

    Claude "That explains why you’re such a bullshitting-"

    Lars "Sir Claude, can you bring the artifact yourself? I’d like to spend some time with Master Sylvian."

    Claude "I’m shocked Captain, choosing Boss Sylvian over me? I wouldn’t have imagined."

    "Sylvian" "I am grateful that you wish to share your time with me, Lars, even if you’re tired from your journey."

    "Sylvian" "Being in your presence is an absolute delight, and I consider myself fortunate to have you by my side. Rory will arrive soon as well so we can spend some time altogether."

    Lars "Master Sylvian's gently touches the brim of his hat and a magnificent bouquet blooms forth. Sunflowers rise proudly, symbolizing triumph, while lavender blossoms intertwine, representing grace in the face of success. Brilliant marigolds add warmth and joy, and clusters of white lilies embody happiness and contentment."

    Lars "He presents me with the bouquet, throwing a smile at Claude. Though I can't interpret his intention, I am grateful for this special gesture. It reveals Master Sylvian's appreciation for his guild members, though I've never seen him give such bouquets to Rory or Claude before."

    Claude "Quite the showmanship, Boss. Though I wonder, if Captain over here got the message in your subtle gesture."

    "Sylvian" "It might be best for you take care of your task, Claude. We’re still not sure of the origins of the artifact you brought and time is of the scenes in situations like this."

    Lars "As Sir Claude takes his leave, his silver lizard tail gracefully sways behind him, reminiscent of the rhythmic movements of the sea. His scales, resembling those of the majestic dragons I often encounter, captivate my gaze with their intricate detailing, despite their diminutive size."

    Lars "However, before I can fully immerse myself in the enchanting display, a sudden voice slices through the air with an excited tone."

    "Rory" "Larsyyy~"

    Lars "Rory, it’s so good to see you again!"

    "Rory" "I almost caught that lizard Claude but he slithered away before I could scold him for teasing you."

    Lars "The figure that emerges from where Sir Claude stood just a few second ago, is none other than Rory, my childhood best friend. True to her lineage as a bull descendent, Rory possesses a fiery temperament and is quick to charge at those who annoy her."

    Lars "Under Master Sylvian's guidance, she apprenticed as the guild's finance hand, helping us to gather funds for every mission through her puppet shows. Our teamwork also grows stronger as we both receive his care."

    "Rory" "Mentor, I just finished up with preparing my puppets for the afternoon show at the market square, but I feel like something is missing but I don’t know what exactly…"

    "Sylvian" "Rory, my dear apprentice. Your puppets, hold secrets untold. Their painted faces, stories to behold. With each delicate movement, a story takes shape. A symphony of imagination, a tapestry we drape."

    "Sylvian" "Let’s work together to find something to inspire or ease your worry before the show, shall we?"

    "Rory" "Thank you, mentor. I don’t know if my family will be there but I don’t want to disappoint them in case I miss the red mark with the show later today. They’re already giving me side glances for not working with them on their weapon forging in the blacksmiths."

    "Sylvian" "Do you need me to talk with them, Rory?"

    Lars "Rory offers a faint smile, her thumbs anxiously twiddling together. The strain in her relationship with her family became evident when she ventured into the puppet business."

    Lars "As the sole heir of the renowned Kyoko blacksmithing family, her decision to pursue a different path than the Dupont family's merchant lineage only exacerbated the existing rivalry and deepened her insecurities."

    Lars "The constant competition between their families continued to cast a shadow over her, leaving her with a bittersweet smile and a lingering sense of unease."

    "Rory" "There’s no need, mentor. They’re the type to be appeased with actions rather than words. The best I can do is prove that I was made for the puppeteer business. When life gets tough, I just have to remember to stay strong and keep charging!"

    "Sylvian" "Haha! That’s right, my dear apprentice, it's not about the size of the bull, it's about the size of its determination!"

    "Rory" "Come on, mentor, I know you’re trying to make the mood lighter but no shorty jokes. I get them enough from a certain someone whose name starts with C for conceited and ends with E for egotistical."

    "Sylvian" "I apologize, Rory. I’ll make up for you by raising your budget for the next show."

    "Rory" "Yay~ Thank you Mentor!"

    Lars "As if summoned by Rory's statement, Claude makes his entrance with the ornate box cradled in his arms. His eyes glimmer with a mixture of anticipation and excitement as he gazes at the artifact. However, rather than keeping it for himself, he extends the box towards me,"

    Claude "I have arrived with a mystery in hand."

    "Rory" "Great, you can leave it here and go take a deep deep dive into the sea over there. I’m sure the hydro beasts for be delighted at your presence amongst them. You could put your merchant skills to use there too, 10 more second to live for a platter of lizard meat."

    Lars "Come on Rory, you don’t really mean that."

    "Rory" "I have never meant anything more in all my bull years."

    Claude "That explains why you’re such a bullshitting-"

    Lars "AHEM! Sir Claude, why don’t you help me out with carrying this box? It’s quite heavy for me to carry."

    "Sylvian" "Are you feeling okay? Let me cast a relief spell for you right now."

    Lars "Instantly, Master Sylvian utters an incantation, causing the artifact box to levitate in midair. I can't help but feel a sense of relief wash over me, grateful that my impromptu lie managed to defuse the conflict and divert everyone’s attention."

    Lars "However, a pang of embarrassment washes over me as I realize that Master Sylvian genuinely believed my lie, thinking that I had made a fuss over a trivial ornate box. when he/Claude brought it over so easily."

    "Sylvian" "Carrying such heavy things might affect your health after all. That was one of the main things my academic years taught me aside from all the other … unique experiences."

    Lars "I need to correct the misunderstanding before it gets out of hand."

    Lars "It’s okay master, I needed to get in my daily dose of exercise too. I don’t want you to think that I’m too weak for one box! More than that, what would our passengers think if their pilot wasn’t able to pick up their luggage or equipment. My parents wouldn’t let me live this down if they ever heard such rumors since they raised me to give my all to take care of those around me especially-"

    "Sylvian" "Lars, I understand., it’s alright…"

    "Sylvian" "Now, let’s use that breathing technique that the humans thought us last time. You remember?"

    "Sylvian" "Breathe for 3 seconds, hold it for 6, and then release it for 9 seconds."

    Lars "Obediently, I follow Master's instructions and feel my breathing gradually slowing down. Just as I am about to launch into another round of ramblings, Sylvian, ever the kind mentor, steps in to guide the situation."

    "Sylvian" "No one is going to think those things of you, Lars."

    "Sylvian" "In every whispered phrase, a friendship blooms. You who cherish your dragon’s well-being, dispelling any gloom. For their safety, you would give your all. A protector, a guardian, answering their call."

    "Sylvian" "If I were a dragon, I wouldn’t want any other handler than you to take care of me."

    Claude "SOOO, what I gather is that Master Sylvian wants to have Lars ride him-"

    "Rory" "Quiet! You wouldn’t dream of understanding my mentor’s cherished feelings for Larsy."

    "Rory" "Even if he did like Lars that way, it’s not as if he would wait years in an unrequited crush just to waste away his life singing little poetry praises and blooming flower out of thin air."

    Lars "I notice Master Sylvian's demeanor change as he quickly turns his head away, as if he’s hiding something. Yet, before I can question further, Rory's next words quickly draw my attention."

    "Rory" "Honestly, you're so annoying that when you were young, your mother pushed your egg to the side of the nest as to not waste the energy keeping you warm. I don’t even know what Lars sees in you that makes him admire-"

    Lars "Oh no! Distraction time."

    Lars "AHHHHHHH- STOP RORY! HOLD ON!"

    Lars "NEVER GONNA GIVE YOU UP, NEVER GONNA LET YOU DOWN. NEVER GONNA RUN AROUND AND DESERT YOU-"

    Claude "As much as I like it when you sing those human songs captain, I think we’re better off witnessing the artifact before the evening sets and little Rory decides to defile my innocent body with her tools."

    Claude "I can see fumes exiting her head as we speak. Oh! ************* I think they got even bigger."

    "Sylvian" "Alright everyone, settle down."

    "Sylvian" "Let me cast a safety spell over the box first, you can never be sure if there are any hidden traps inside."

    Lars "Master Sylvian waves his hands gracefully around the box, a display of his magical prowess. However, after a few seconds of sparking light and anticipation, the box remains unresponsive, devoid of any notable reactions."

    "Sylvian" "No traps or enchantments detected. It seems we’re in the clear. Let’s unveil the treasure within."

    Lars "Master Sylvian carefully opens the ornate box, unveiling a mesmerizing sight. Inside rests a long necklace adorned with an array of thick bands and intricate chains, all nestled within a plush cloth. However, the centerpiece of the necklace steals everyone's attention—the stunning red gem that emanates a captivating ruby hue."

    Lars "Its allure is so powerful that everyone was momentarily enchanted by its beauty, completely overlooking the intricate engravings etched along the sides of the chains. Engravings bearing an ancient language, harkening back to the time of the original descendants."

    Claude "Before anyone starts their inspection, I promised our dear captain he’d be the first person to hold it."

    Lars "I direct my gaze towards the opened box, feeling the weight of everyone's anticipation upon me. With a sense of intrigue, I carefully lift the necklace from its resting place, noting its surprisingly light size despite its visually hefty appearance. As I hold it in my hands, all eyes remain fixed upon me."

    Lars "Thanks, Sir Claude. Wow! Look at the detailing on this artifact. It’s truly a work of art."

    Claude "Indeed, it’s a testament to the skill and craftsmanship of the ancient civilization that created it. But who exactly? we have no idea about its origins yet."

    Claude "Not to mention, I could never let go of such a mysterious prize, I need to uncover its secrets all for myself…"

    Lars "Sir Claude's expression undergoes a striking transformation, shifting from one of casual curiosity and playful mirth to that of intense obsession. His eyes fixate unwaveringly on the artifact, a glimmer of determination and fervor dancing within them."

    Lars "It is no secret that Claude possesses a deep-seated fascination with challenges and trials, often drawn to the enigmatic and mysterious. Though he seldom shares the reasons behind his unwavering obsession, his eyes betray his inner excitement whenever faced with such an opportunity."

    Claude "…Ahem, with the help of our prestigious scholar as well of course!"

    Claude "Boss Sylvian, you have quite the reputation in the academic world for discovering the connection between our realm and Earth. Especially the cycle of reincarnations connecting the two."

    Claude "If someone were to discover the potential behind this artifact, it would be none other than you."

    "Rory" "Ugh, quit trying to suck up and get close to my Mentor with your scale-rotten face."

    Claude "Weren’t these the very same scales you took for your dolls? Admit it, you just don't measure up to scale. Specifically, my scales!"

    Claude "I was under the impression that they even made you gain a great show last time with your puppets."

    Claude "Hmm, what was it called again? Boring-ina? Boorish-ina? Banal-ina? -"

    "Rory" "It was BRITTINA, you dagger-mouthed, scale-brained, bark-bellied, algae-breathing gullet on legs-"

    Claude "I’d lower myself to your idiotic level, but then you’d beat me with experience-"

    Lars "Come on guys, it’s time to stop. We’re losing daylight over here."

    Lars "However, neither side showed any signs of stopping their retort. After all, the first to stop would be the first to lose and their competitive nature fueled by their family legacy wouldn’t allow them this leeway."

    Claude "It’s no wonder that your family legacy is going to die with you. I wouldn’t put myself in the low position of insulting you, though it's a huge plus if I do, but whoever told you to \"just be yourself\" gave you awful advice. You need to reconsider your life choices over here."

    "Rory" "Heh, I didn’t know I had to seek life advice from a nepotism embodying lizard who never strived to do anything separate from his parents wishes. Look I think we all have something to bring to this conversation, but I think what you should bring is silence. Especially when all you ever have to add is self-inserted praise and narcissism."

    "Sylvian" "Both of you, it’s time to stop."

    Lars "Master Sylvian's commanding voice reverberates through the air, instantly commanding the attention and quieting the bustling atmosphere. Though his usual demeanor is one of calm and collected composure, there are moments when he employs his authoritative voice to instill a sense of tranquility and order among those around him."

    Lars "It is a fascinating contrast to witness, as his typically serene nature aligns seamlessly with his position as the guild leader to command respect and bring about a sense of calm."

    "Sylvian" "Let us embrace empathy’s grace and refrain from jesting, for each soul carries its own unique beauty. Whether it be lizards, foxes, swans, or bulls."

    "Rory" "Sorry, Mentor. Looks like I’ve overstepped a bit."

    Claude "It’s never a good move to annoy your benefactor. Apologies, Boss."

    Lars "As Claude and Rory move away to not bump heads again, I quietly moves towards Master Sylvian and whisper in a quiet tone."

    Lars "Thanks for easing off the tension, Master Sylvian. I’ve spoiled Rory too much, and it gets out of hand when they start bickering."

    Lars "A shy smile graces Master Sylvian's lips as he gently rests his hands on my shoulders. The feathers of his swan wings delicately brush against my back, imbuing me with a profound sense of tranquility and ease."

    "Sylvian" "No problem at all, Lars. I might not understand your relationship with Rory well as you both are best friends from a young age. But I would hate to see a rift between us as guild members."

    "Sylvian" "Your bond with Rory holds a treasure untold. A childhood’s embrace worth more than gold. I wish I could have that kind of equal friendship too-"

    Lars "What are you talking about, Master?"

    Lars "Are you saying we aren’t friends?"

    "Sylvian" "… we are Lars, it’s just that as your superior, I don’t we can have that equal relationship that you have with-"

    Lars "You know, even if I’m just your junior. You’re my cherished friend, though I value you first and foremost as the boss, I still enjoy how you are kind to everyone, share your poetry with them and give them gifts."

    Lars "Summoning all my courage, I move closer and grasp Master Sylvian's hands, locking my gaze with his. The initial shock on his face gives way to a warm and genuine smile, a flicker of happiness illuminating his eyes."

    Lars "In that moment, I can sense a profound understanding between us, transcending words and barriers. It is a silent acknowledgement of the trust and respect that exists between a master and his apprentice, a bond forged through shared experiences and admiration."

    Lars "Sorry if that sounds like I’m sucking up to you or asking you for something, which I’m not in any way! It’s just that my mom always told me to be straightforward when taming wild dragon species, especially the ones with thorns on their lateral muscles. Their venom comes from there, and it really hurts when they start dangling your legs off the side, which even caused me to have a scar on this part of my right leg, and-"

    "Sylvian" "Hahahaha!"

    "Sylvian" "Ah, the delight you bring to my life Lars, what would I do without you to brighten up my day."

    Lars "Master Sylvian wipes away the tears that have gathered around his eyes."

    Lars "As if understanding my need for reassurance, he gently pets me on the head and softly rubs my ears. The sensitivity of my ears amplifies the affectionate gestures, creating a moment of intimate connection between us."

    "Sylvian" "Don’t worry about it, it’s just that It's hard to bring out the words that bubble up in your throat sometimes."

    "Sylvian" "But I do appreciate your efforts, I just hope that I can be the recipient of your more endearing efforts as well."

    Lars "Uhm, what do you mean, Mast-"

    Lars "Suddenly, Rory appears from behind me, her strong arms enveloping me in a tight embrace. Claude, not one to be left out, joins in and approaches us with a mischievous grin on his face."

    Lars "Master Sylvian takes hold of the artifact, his eyes filled with a mix of curiosity and determination."

    Lars "Fully aware of the significance and potential of this mysterious item, he understands the need to concentrate all his attention on unraveling its history and unlocking its hidden powers."

    "Sylvian" "I’d like to observe this a bit more in my lab."

    "Sylvian" "A curious trinket, its secrets untold. An odd accessory with immense power. To shape time’s fragments, to weave its essence."

    "Sylvian" "It eerily resembles an artifact that I had previously seen in the academic domain. A one-of-a-kind necklace with a similar gemstone belonging to a family of dragons with our very own half-human, half-animal traits as descendants."

    "Sylvian" "I haven’t heard of them in quite some time, and though the color of its gem contrasts the descriptions I’ve heard and read, the artistry and written etchings are quite similar. it’s something worth researching."

    "Sylvian" "Speaking of which, how much did you exchange for it, Claude? We need to see if the funds from Rory’s recent puppet show will be able to cover the costs."

    Claude "Well, a merchant may only exchange for what they’re willing to offer."

    Claude "However, the infamous Claude can overcome any trial as long as he wishes for it. But basically, I got it for free since the seller was begging me to take it from me."

    Claude "Ah, the misery of knowing the world will fit into the palm of my hand as long as I aim for it."

    Lars "Rory's eyes widen to an almost comical extent, as if they’re on the verge of rolling out of their sockets."

    Lars "Master Sylvian merely closes his eyes, whether he’s focusing on what Sir Claude is saying or mentally preparing himself for any upcoming conflicts, I can’t tell."

    "Rory" "Ernest Jones called and said he wants his god complex back, or better yet-"

    "Rory" "Ovid left a voicemail saying he’s issuing the world a mental refund for the amount of narcissism you’re breathing into the world."

    Claude "Getting real creative with the insults, aren’t you? Make up another absurd statement now won’t you?"

    "Sylvian" "What if… did you steal the artifact?"

    Claude "Now that’s just blasphemy! I could never. I swear on my parent’s graves-"

    "Rory" "Your parents aren’t even dead yet!"

    Claude "You didn’t let me finish."

    "Rory" "Not going to."

    "Rory" "Come to think about it, mentor, can I take this artifact for a spin before you put it in your lab?"

    "Rory" "This design is perfect for one of my dolls. I can create a new puppet based on these intricate patterns and symbols. It will be a showstopper!"

    "Sylvian" "If you feel inspired by this artifact, then by all means, go ahead."

    Lars "That’s a great idea! We could even visit your puppet show stall and see what magic you will create. It’s been some time since I last played with the kids as well."

    Claude "Why don’t you wear the necklace for now, Captain. The red suits you after all, reminds of the red string of fate-"

    "Rory" "Stop with the flirting-"

    Lars "I take this moment to put on the necklace, the gemstone’s ruby color captures my attention but soon enough I hear my name being called by the group."

    Lars "The four of us make our way towards the open area adorned with numerous stalls. Sylvian deliberately slows his steps, keeping a watchful eye over the rest of us as we continue ahead."

    Lars "Meanwhile, Claude and Rory pick up their pace, engaging in a competition to see who can reach the stall first. Their banter fills the air as they exchange witty remarks, not holding back on their rivalry."

    Lars "Hopefully, it’ll be another day without any troubles here in Zephyr and ‘Custodes Sylvae’."

    Lars "The town square pulsed with vibrant energy, a captivating tapestry of stalls adorning the cobblestone pathway. Within this bustling scene, a kaleidoscope of merchants enticed passersby with their wares."

    Lars "The tantalizing scents of delectable dishes wafted through the air, while clothing boutiques showcased garments of exquisite craftsmanship."

    Lars "Among them, the craftsmen descendants, most notably the bull and lizard families, proudly exhibited their meticulously crafted trinkets, their rivalry hidden beneath the surface of high price tags."

    Lars "The simmering tension between Claude and Rory's families had persisted through generations, and they avoided each other with apparent disdain."

    Lars "Fortunately, we managed to blend seamlessly into the crowd, escaping their notice."

    Lars "Amidst the diverse crowd of people, encompassing both humans and descendants, we navigated our way through the bustling hub. It posed a unique challenge to navigate through the various tails, wings, and horns of different species."

    Lars "Yet, after riding countless dragons and growing accustomed to their scales, a few feathers or fur proved to be manageable obstacles."

    Lars "Now that I think about obstacles…"

    Lars "By the way Rory, what’s our plan for today?"

    Lars "It was no secret that Rory’s performances provided the main source of funding for our expeditions and negotiations, making it a collective mission for all of us to advertise her show today."

    Lars "The well-being of our guild dragons heavily relied on those funds, and I cannot bear the thought of them going hungry or enduring any discomfort. I would willingly starve myself before allowing such a situation to come up."

    "Rory" "I was thinking we could focus on a kids show for today Larsy, you guys can gather the kids up ahead near the food stalls. By the way, don’t forget to buy me one of those Firepecker kebabs on the way back!"

    Claude "It’s always eye opening to see how you try to appease your family lifestyle, little Rory. Firepeckers? Are your puppets made of money by any chance? I can’t let Captain over here spoil you too much when I’m around, now can I?"

    "Rory" "Listen here you-"

    Lars "Suddenly, a delightful aroma caught my attention, wafting through the bustling marketplace. The captivating scent of Firepeckers grilling a mouthwatering variety of meats and vegetables filled the air."

    Lars "These fascinating creatures, originally miniature phoenixes with a dark, charcoal-like hue, possessed a unique talent for igniting objects. The higher class often used them to add a touch of theatrics when cooking, delighting in their fiery displays."

    Lars "Humans used to call them ‘fire-breathing hibachi birds’ since the impression reminded them of a similar concept from back on Earth."

    Lars "Reminds me… Sir Claude, against his luxurious upbringings, always preferred the alternative cooking methods. He found solace in dragon blaze machines, captivated by their bold approach."

    Lars "For him, it was an adventurous quest to discover new culinary experiences and expand his gastronomic knowledge. The reason behind his choices…"

    Lars "I wish I could know especially since he came up with a new reason each time just to tease me."

    Lars "Now that I think about it, the artificial dragon blaze machines were quite the trend during my training years. They were crafted by the scholarly minds of the Tower of Magicians in Zephyr, to replicate the image of dragons."

    Lars "It’s fascinating to think that Master Sylvian, esteemed for his scholarly genius, had a connection to this unique invention despite his age at the time."

    Lars "However, he rarely speaks about his departure from academia. It always left me curious about the reasons behind his choice. Perhaps, in time, he would grow comfortable enough to share his story."

    Lars "But, now I’m curious about both of those question. Who do I ask while we reach Rory’s stall?"

    Lars "Before long, the collective footsteps of our group came to a halt, a unanimous signal that we had arrived at our destination."

    "Rory" "Here we go! A special stall for special puppets who actually have a purpose in life unlike a certain someone."

    "Rory" "Not to mention, Brittina and Alex were very happy, enthusiastic, and even enthralled to enhance their looks with the help of Claudy over here."

    "Rory" "I did want to pluck out the lizard’s eyes for Agatha, but it’s very hard to do that in his sleep especially since he’s such a light sleeper."

    Claude "So, you’ve been watching over me in my sleep? Naughty little Rory."

    "Rory" "Somewhere in Zephyr, a tree is tirelessly producing oxygen for you. I think you owe it an apology because of all the air pollution you’re creating with that mouth."

    Claude "I could excuse the scale stealing incident and the hair cutting fiasco because I’m so benevolent."

    Claude "However, night peeking is a no-no. Unless it’s my lovely Captain who does it."

    Lars "Ugh…"

    "Sylvian" "I think it’s time to stop teasing Lars, Claude. You’re making him uncomfortable."

    Lars "That’s right, listen to him. You might have a so-called ‘third eye’ but Master Sylvian’s way better at reading my cues than you."

    Lars "Sir Claude made a show to smile even brighter than before, was it a display of sarcasm? A mental show of competition for more teasing? I can’t tell…but soon enough, he lets out a light sigh."

    Claude "…fine, I suppose. Can’t go against out esteemed Captain’s wishes."

    Claude "But you can’t be serious when saying that Master Sylvian reads you better than I do."

    Lars "Sir Claude unexpectedly outstretches his hand, and before I know it, our hands are entwined. He gently pulls me closer, our bodies drawing near until our shoulders touch, creating a subtle connection between us."

    Lars "In that moment, I couldn't help but notice a figurative storm cloud forming above Master Sylvian's head. His eyebrows knit together, and his arms crossed."

    Lars "As if reflecting Master Sylvian's mood, delicate hyacinth blossoms, with a regal purple hue, lined the brim of his hat. However, with each subtle shake of his head, the petals wilted and withered away, mirroring the disappointment etched on his face."

    Lars "But why?"

    Lars "I’m not always on board with Sir Claude’s shenanigans, but it’s often easier to go along with his wishes rather than challenge him."

    Lars "He likes the thrill of competition so removing that factor always helps with him loosing interest."

    Lars "Master Sylvian knows that as well, so why would he…show such an expression?"

    Claude "Whether it’s the way your cute tail wags around when you start rambling or how your ears perk up while listening to human’s tales, I can tell each and every one of them apart."

    Lars "He reached out with his scaly hand and gently traced his fingers along the contours of my ears. I could feel myself slowly heating up, my ears and tail were more sensitive that I wished for."

    Claude "I don’t need a ‘third eye’ to understand you, Captain. However, I still like to tug on the line between us."

    Claude "I ensure you that this line will soon enough turn into a thread of destiny for us."

    Lars "Alright! that’s enough jokes Sir Claude-"

    Lars "As if urged by my sudden outburst, Master Sylvian follows suit."

    "Sylvian" "Claude, it’s time to stop your act."

    Lars "Was Master waiting for me to stop Sir Claude first?"

    "Sylvian" "Never use someone’s weaknesses as a weapon against them, for it reflects your own character more than theirs."

    Claude "Boss, as much as I adore your poetry and philosophical quotes, I have to stand my ground when it comes to teasing Captain over here."

    Claude "You see, it’s fun for me to see which of his buttons I can push."

    Claude "Besides, Boss, any person who tries to be good all the time, like you, is bound to come to ruin."

    Claude "I would even dare say that you’re the one who is harboring the most dangerous inner feelings among all of us."

    Claude "Because, at least, I can release my emotions by having fun with my Captain."

    Lars "…my Captain???"

    Claude "Yet, you only ever have your flowers to bear your secrets with."

    Claude "I think it’s about time for your head to equally start fuming like little Rory over here."

    "Rory" "Hmph!"

    Claude "Not to mention, isn’t it time for you to admit to Lars that you have a crush-"

    Lars "But before he has a chance to finish his sentence, Master Sylvian’s voice cuts through."

    "Sylvian" "Claude."

    "Sylvian" "I treasure you as a guild member of “Custodes Sylvae,” but even still, your mouth resembles that of a snapdragon during moments like this."

    "Sylvian" "A certain amount of grace as the sides of deception press together to bloom in beauty."

    "Rory" "Uhm, Mentor, I don’t understand what’s going on here. But can we stop bickering for a second?"

    Lars "Rory’s right, it’s not like you two to argue like this…"

    Claude "It seems that some things-"

    "Sylvian" "-are overdue for the both of us."

    "Rory" "If you say so, in the meanwhile…"

    "Rory" "You guys try to gather the kids while I set everything up."

    Lars "I made my way through the bustling groups of kids, determined to gather their attention. The excitement in the air was palpable as their laughter and chatter filled the space. With a deep breath, I projected my voice, shouting out an announcement that echoed through the crowd."

    Lars "HEY EVERYONE, I’M BACK! THE PUPPET SHOW IS GOING TO START SOON!"

    Lars "The moment I finished my announcement, I was instantly bombarded by a swarm of enthusiastic children. They ran towards me, their voices rising in a crescendo of excitement as they vied for my attention."

    Lars "Little hands tugged at my sleeves, pulling me in different directions, each child eager to share their thoughts or be part of the upcoming event."

    Lars "Amidst the joyful chaos, I could see Sir Claude and Master Sylvian observing from afar, their watchful eyes filled with amusement and glint of … something else that I can’t quite put my finger on."

    "Random" "Yay! Lars is back from his trip."

    "Random" "I missed you, Lars; my dragon has been messing with my toys recently. You definitely have to help!"

    "Random" "Lars! Don’t forget we still have our race for the afternoon. You have to help me win, please!"

    Lars "Haha this all takes me back to the old days to back when I was a kid."

    "Sylvian" "I hope I’m not bothering you in the middle of your affairs, Lars."

    Lars "Of course not Master, this would be the perfect time to show off my skills to you in person. I’m the fastest amongst everyone here after all."

    Claude "Hmm, how typical of our dear captain to compare himself with mere children."

    Lars "You could leave for all I care, Sir Claude. I’m still upset because of the way you teased me last time."

    Lars "By this time, both guild members were already by my side. Sir Claude, with his innate charisma, effortlessly charmed the children who surrounded us. Meanwhile, Master Sylvian, despite his current focus on flower magic, mesmerized the children with his expertly performed magic tricks."

    Claude "Awe, I’ll pretend to be hurt but while I’m still here, take my advice. You have to challenge yourself more, Captain."

    Claude "You won’t be able to show off your talents to anyone when you spend your time with these childish competitions. How will you be able to prove yourself to the elite if you only ever rival with kids?"

    Lars "Not everything is a contest to prove oneself, Sir Claude."

    Lars "Sometimes, I can be content with just playing around and enjoying the moment as is. Isn’t that right, Master?"

    "Sylvian" "Success without heart can be empty and hollow, Claude. I treasure you as a guild member of “Custodes Sylvae,” but even still, I worry for the sake of your dependence on wanting to carry yourself differently from your family legacy."

    Lars "Family legacy …"

    Lars "It was certainly true that Sir Claude had the tendency to act out against his family’s wishes from time to time but according to the rumor mills, he didn’t have a reason too."

    Lars "The Dupont family, a lovely couple of lizard descendants, never strived Claude of love and affection which was something that he confirmed as well."

    Lars "However, he had the notion of removing them from his character from time to time, as if he were born from a nameless hermaphrodite and all he ever existed as was as ‘Claude’ and not ‘Claude Dupont’."

    "Sylvian" "If you merely pursue rivalry to prove your self-worth to unknown faces, it will only be a matter of time, before the present escapes your reach for the past left behind."

    Claude "Forgive the insolence, Boss. But, isn’t that lack of ambition precisely why you’re here with us today instead of boasting around the academia halls?"

    Lars "Sir Claude, this is not the right time or place to delve into Master’s past."

    "Sylvian" "Hold on Lars, I want to hear the rest of what Claude has to say."

    Lars "If you say so…"

    Claude "Though I value your presence in our guild and your support of my endeavors Boss, you have let go of all your desires and merely follow the direction that your flowery path takes you."

    Claude "But, you see, if you’re not determined about what you want, someone else could come and achieve your dream instead."

    Lars "I catch Sir Claude throwing a peek at me but he quickly switches his focus back to Master Sylvian."

    Lars "When it came to dreams, Master Sylvian had garnered quite the reputation as the 'genius of the century' during his tenure at the Tower of Magicians in Zephyr."

    Lars "Although he rarely spoke about his past experiences, a glimpse into his emotions could be seen in the way his feathers drooped and his shoulders slumped with a sense of dejection whenever the topic came up."

    Lars "Even his perpetual hunched posture served as a constant reminder of his time as a prestigious state magician. A time where he would work himself to the bone day and night with no rest in between."

    Lars "Despite his current focus on flower magic, it was evident that Master Sylvian had a different area of expertise in the past. The secrets and stories behind his prior magic remained locked away, untold."

    Lars "The formation of our guild seemed to be a deliberate decision he made in response to his experiences as an academician, though he seldom delved into the specifics."

    Lars "It was as if those memories held a weight he carried silently, reflected in his demeanor and choices."

    Claude "It’s in the very motto of ‘Custodes Sylvae’ after all."

    Claude "Discere, cogitare, agere- the triad of wisdom. Learning enriches the mind, and thinking sharpens it, but it is through action that we truly manifest our knowledge and shape our reality."

    Claude "You have the first two down but you’re running away from the third step."

    Claude "Isn’t that right Captain?"

    Lars "…"

    "Sylvian" "What you’re saying holds grains of truth, Claude."

    "Sylvian" "Without love or ambition, our lives languish in the shadows of mediocrity."

    "Sylvian" "They ignite the fire within, propelling us to venture beyond our limits, to dream and to create, shaping a life of purpose and fulfillment."

    Claude "So, you do agree-"

    "Sylvian" "However, …"

    "Sylvian" "Amidst our pursuit of them, let us not overlook the tranquility of mediocrity."

    "Sylvian" "For not every path must lead to grand creations or extraordinary feats."

    "Sylvian" "In embracing simplicity, we find contentment, and in cherishing the ordinary, we discover the beauty of a life unburdened by the pressures of relentless ambition."

    Claude "Aren’t you saying that only because you were burnt out and having nothing else to pursue?"

    Claude "If you always treasured this so-called ‘contentment’ why did you decide to spread your name onto society as the top academic of Zephyr?"

    Claude "You could have simply stuck to the bottom ranks and let your life aimlessly pass by without ever achieving something or falling in love with a certain someone."

    Lars "I felt my fur stand on edge at the sudden statement."

    Lars "What’s he talking about, Master? You’re in a relationship with someone?"

    Claude "Focus here Captain, we can talk about that later. Unless you’ve already taken someone’s side?"

    Lars "Uhm, you’re both people that I deeply admire and I don’t really want to-"

    Claude "Don’t? or can’t think up of your personal opinion?"

    "Sylvian" "Pay him no mind, he’s just upset for himself."

    Lars "I agree with Master Sylvian."

    Lars "I think what Master says is true about enjoying what we want instead of simply going after it for the challenge."

    Lars "I like hanging out with my dragons even if we weren’t in the middle of an expedition or mission and I wouldn’t change my relationship with them for the world."

    Lars "Going after artifact hunts and transporting passengers without an ounce of love seems depressing to me."

    "Sylvian" "Thankfully, Claude’s influence hasn’t rubbed on you too much."

    "Sylvian" "Amidst the circle we tread, like the Ouroboros we find. Forever chasing our tails, destiny intertwined."

    "Sylvian" "I’m always impressed by how well you articulate your words, my dear junior. Maybe, we can discuss these philosophies and more once we have free time."

    Lars "Haha, I would love to spend time with you but Spotsy needs me most, don’t you think so?"

    Lars "She’s had a long flight after all."

    "Sylvian" "I can’t deny that I’m bit disappointed…"

    "Sylvian" "However, it’s one of the things that I like seeing you do Lars."

    "Sylvian" "It’s amongst my wishes to someday be a recipient of the same adoration you hold for your dragons."

    Lars "I let out a little laugh. Maybe my mind needed a bit of humor to escape the deeper side of the abyss that I was looking at to find my answer."

    Lars "No copying jokes from Sir Claude, Master. It’s best if we call a truce with everyone for now."

    Lars "I agree with what Sir Claude says."

    Lars "It’s not fair to not fight for what you love and desire."

    Lars "I could admire my dragons all day and night but if I never take that leap of fate to touch them and show them my feelings directly, then I’ll only ever be walking in a circle."

    Lars "I also can’t imagine going a day without learning about the new dragon species out there."

    Claude "Glad to see that you’ve learnt a few things about my motto of life, Captain. It’s not complete, but I’ll teach more later, in private."

    Lars "Haha, I would love to spend time with you but Spotsy needs me most, don’t you think so?"

    Lars "She’s had a long flight after all."

    Claude "At this rate, I don’t think I’ll ever be able to compete with your love for dragons, Captain."

    Claude "But I’ll do my best to win you over, and spoil you rotten the same way you do for your dragons."

    Lars "I let out a little laugh. Maybe my mind needed a bit of humor to escape the deeper side of the abyss that I was looking at to find my answer."

    Lars "No teasing for now, Sir Claude. It’s best if we call a truce with everyone for now."

    Lars "While I was engrossed in our conversation, Rory approached us with a somewhat worried expression etched on her face."

    "Rory" "Guys, why isn’t anyone coming, where are the kids?"

    Lars "Ah, I gathered them all here! As you can…see?"

    Lars "But… why? In front of us stood unmoving statues, each frozen in time."

    "Rory" "Is this a joke? Was there a surprise flash mob that I wasn’t aware of?"

    "Rory" "Clauuudy, did you bribe people again to pull a prank on me. If so, then you’re in for a beating-"

    Claude "As much as I would love to take credit for such an event, I have no clue what’s happening either."

    "Sylvian" "A strange phenomena is happening, it seems."

    Lars "What does that mean, Master? What’s going on with everyone?"

    Lars "I instinctively reach out and begin shaking a few of the figures resembling frozen children."

    Lars "Kids, come on, the joke isn’t funny anymore. We’re getting really worried over here."

    Claude "What could have suddenly happened here?"

    Lars "In the midst of my attempts to shake the statues, a peculiar sensation coursed through me."

    Lars "I felt the necklace I was wearing growing warmer, its temperature gradually rising."

    Lars "Intrigued and compelled, I shifted my attention towards it. Seems like Rory noticed it as well."

    "Rory" "Hold up! What’s happening to the artifact right now? Take a look everyone. It’s as if it’s shining…"

    Lars "Instantly, everyone’s gaze was fixated upon me."

    Lars "Master Sylvian's face bore a deep concern, his furrowed brow revealing his worry."

    Lars "On the other hand, Sir Claude's eyes burned with fire, a half-grin playing at the corners of his mouth."

    "Rory" "Are we under a weird spell right now? It’s as if…we’re the only people moving and everyone else is frozen in time. Is it related to Larsy’s necklace? What’s going on Mentor?"

    "Sylvian" "I have only ever heard of one artifact having the ability to such a thing."

    "Sylvian" "However, the color of the gem in our necklace is different from that I which remember."

    "Sylvian" "Even then, why would such an effect happen so suddenly?"

    Claude "I didn’t hear anything about that from my customer either, there was nothing like this when they handed over the artifact to me."

    Lars "What do we do now? What’s going to happen to them?"

    "Sylvian" "Steadfast everyone, calm yourselves down."

    "Sylvian" "The brave person is not the one who feels no fear, but the one who conquers that fear. Let’s do our best to figure this out."

    Lars "Me too Master! I’m the strongest one among us, I’ll try to protect us in case something goes south."

    Claude "I can try to-"

    "Rory" "Guys, wait!"

    "Rory" "Can anyone else see that shadowy figure over there?"

    Claude "I recognize that too little Rory. However, it’s unlike anything I’ve seen before…"

    "Rory" "I’m not in the mood for jokes, you scale rotten-"

    Lars "I think we’re being watched by someone."

